apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: sit722task72p.azurecr.io/book_catalog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DATABASE_URL
              value: postgresql://sit722_72p_user:qiV6wCtM8bRcCBjKXxZUHDQPUcziTiYO@dpg-crld5sij1k6c73fqrri0-a.oregon-postgres.render.com/sit722_72p
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: sit722task72p.azurecr.io/inventory_management:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 81
          env:
            - name: PORT
              value: "81"
            - name: DATABASE_URL
              value: postgresql://sit722_72p_user:qiV6wCtM8bRcCBjKXxZUHDQPUcziTiYO@dpg-crld5sij1k6c73fqrri0-a.oregon-postgres.render.com/sit722_72p
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 81
      targetPort: 81
